### ISSUE TITLE
Djangae project stops working with SDK 149.0.0

### ISSUE THREAD

**Issue by seawolf42** [potatolondon/djangae#907]
I have a project that works fine with version 148.0.0 of the Google SDK. It is a very simple project. I have the following packages installed:

```
$ pip freeze
appdirs==1.4.3
djangae==0.9.9
Django==1.8.18
django-autometrics-nonrel==0.9.2b1
olefile==0.44
packaging==16.8
Pillow==4.1.1
pyparsing==2.2.0
six==1.10.0
```

When I try to run the project in any way (`python manage.py test`, for example) using Google's 149.0.0 (or greater) SDK, I get an exception:

```
$ python manage.py shell
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/seawolf/dev/py_virtualenv/autometrics_nonrel/lib/python2.7/site-packages/djangae/core/management/__init__.py", line 62, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + other_args, **overrides)
  File "/Users/seawolf/dev/py_virtualenv/autometrics_nonrel/lib/python2.7/site-packages/djangae/core/management/__init__.py", line 42, in _execute_from_command_line
    **sandbox_overrides
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/seawolf/dev/py_virtualenv/autometrics_nonrel/lib/python2.7/site-packages/djangae/sandbox.py", line 409, in activate
    with SANDBOXES[sandbox_name](**kwargs):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/seawolf/dev/py_virtualenv/autometrics_nonrel/lib/python2.7/site-packages/djangae/sandbox.py", line 166, in _local
    storage_path = devappserver2._get_storage_path(options.storage_path, configuration.app_id)
AttributeError: 'module' object has no attribute '_get_storage_path'
```

Here's the full upgrade-and-test sequence showing the failure (I snipped a few tables and irrelevant output from the upgrade but kept items that seemed possibly important):

```
$ gcloud components update --version 148.0.0

Your current Cloud SDK version is: 149.0.0
You will be upgraded to version: 148.0.0

<snip>

Update done!

To revert your SDK to the previously installed version, you may run:
  $ gcloud components update --version 149.0.0

$ python manage.py shell
INFO     2017-04-30 14:22:19,580 blobstore_service.py:75] Starting blobstore service on localhost:8080
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> exit()
INFO     2017-04-30 19:22:21,996 api_server.py:700] Applying all pending transactions and saving the datastore
INFO     2017-04-30 19:22:21,997 api_server.py:703] Saving search indexes
$ gcloud components update --version 149.0.0

Your current Cloud SDK version is: 148.0.0
You will be upgraded to version: 149.0.0

<snip>

The following release notes are new in this upgrade.
Please read carefully for information about new features, breaking changes,
and bugs fixed.  The latest full release notes can be viewed at:
  https://cloud.google.com/sdk/release_notes

149.0.0 (2017-03-29)
  Breaking Changes
      ▪ The Cloud SDK installer on nix will no longer attempt to update your
        RC files in non-interactive mode.
      ▪ Support for creating/updating legacy sinks has been removed from
        gcloud beta logging.

  Cloud SDK
      ▪ SHA256 checksums, instead of SHA1 checksums, are now being published
        for Cloud SDK versioned archives and other downloadable assets.

  Firebase Test Lab
      ▪ The gcloud test commands have been promoted to GA and renamed gcloud
        firebase test .... All gcloud beta test ... commands are deprecated.
      ▪ The preferred way to specify test devices is the new --device
        argument, which allows more precise control over which device
        dimensions are included in a test matrix. See gcloud firebase test
        android run --help and gcloud topic arg-files for details.

  Google App Engine
      ▪ Updated Python SDK to version 1.9.51.
      ▪ Support Server Name Indication (SNI) for remote API shell.

<snip>

148.0.1 (2017-03-24)
  Google Cloud Functions
      ▪ Fixed a bug where gcloud beta functions deploy did not work without
        the --region flag specified.

<snip>

Update done!

To revert your SDK to the previously installed version, you may run:
  $ gcloud components update --version 148.0.0

$ python manage.py shell
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/seawolf/dev/py_virtualenv/autometrics_nonrel/lib/python2.7/site-packages/djangae/core/management/__init__.py", line 62, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + other_args, **overrides)
  File "/Users/seawolf/dev/py_virtualenv/autometrics_nonrel/lib/python2.7/site-packages/djangae/core/management/__init__.py", line 42, in _execute_from_command_line
    **sandbox_overrides
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/seawolf/dev/py_virtualenv/autometrics_nonrel/lib/python2.7/site-packages/djangae/sandbox.py", line 409, in activate
    with SANDBOXES[sandbox_name](**kwargs):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/seawolf/dev/py_virtualenv/autometrics_nonrel/lib/python2.7/site-packages/djangae/sandbox.py", line 166, in _local
    storage_path = devappserver2._get_storage_path(options.storage_path, configuration.app_id)
AttributeError: 'module' object has no attribute '_get_storage_path'
```

**Comment by seawolf42** [comment]
You can see the specific errors locally with the following project: https://github.com/seawolf42/django-autometrics/commit/0dbde98b33d9f52e2c0322a2661f6141ee293666

**Comment by davidwtbuxton** [comment]
Hi,

Can you try with the current head of the master branch please? Changes were made as part of issue #880 to support SDK 1.9.51, which was merged after the 0.9.9 tag.

David B.

**Comment by briva** [comment]
Same pb solve with the last head of djangae.

Now I have a new issue when i launch my tests :

```
File "lib/djangae/test_runner.py", line 118, in init_testbed
    getattr(bed, init_name)(**stub_kwargs.get(init_name, {}))
  File "/Users/user1/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/ext/testbed/__init__.py", line 590, in init_images_stub
    raise StubNotSupportedError(msg)
StubNotSupportedError: Could not initialize images API; you are likely missing the Python "PIL" module.
```

**Comment by seawolf42** [comment]
The PIL issue is different... if you install Pillow locally do you still error?

jeff

**Comment by seawolf42** [comment]
It appears to work with the latest Google SDK (154.0.0), so that's good. Thanks!

```
$ gcloud --version
Google Cloud SDK 154.0.0
app-engine-python 1.9.52
bq 2.0.24
core 2017.05.01
gcloud 
gsutil 4.25

$ $HOME/dev/py_virtualenv/pt/bin/python manage.py runserver
INFO     2017-05-04 07:11:29,619 blobstore_service.py:74] Starting blobstore service on localhost:8012
Validating models...

System check identified no issues (0 silenced).
May 04, 2017 - 12:11:30
Django version 1.8.18, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

INFO     2017-05-04 12:11:30,162 devappserver2.py:692] Skipping SDK update check.
INFO     2017-05-04 12:11:30,163 api_server.py:272] Starting API server at: http://localhost:8010
INFO     2017-05-04 12:11:30,172 dispatcher.py:205] Starting module "default" running at: http://localhost:8000
INFO     2017-05-04 12:11:30,187 admin_server.py:116] Starting admin server at: http://127.0.0.1:8011
^CINFO     2017-05-04 12:11:32,924 api_server.py:863] Applying all pending transactions and saving the datastore
INFO     2017-05-04 12:11:32,925 api_server.py:866] Saving search indexes
INFO     2017-05-04 12:11:33,376 api_server.py:863] Applying all pending transactions and saving the datastore
INFO     2017-05-04 12:11:33,376 api_server.py:866] Saving search indexes
```

The first time I tried the new bits was with Google's SDK version 148.0.0 and the commit for the issue you referred to; in that configuration I got a new error:

```
$ gcloud --version
Google Cloud SDK 148.0.0
app-engine-python 1.9.50
bq 2.0.24
bq-nix 2.0.24
core 2017.03.17
core-nix 2016.11.07
gcloud 
gcloud-deps 2017.03.17
gcloud-deps-darwin-x86_64 2017.02.21
gsutil 4.23
gsutil-nix 4.18

$ pip install git+https://github.com/potatolondon/djangae.git@86433d087f1f6a53e62f6bac6cabe0a6c1368b4f
Collecting git+https://github.com/potatolondon/djangae.git@86433d087f1f6a53e62f6bac6cabe0a6c1368b4f
  Cloning https://github.com/potatolondon/djangae.git (to 86433d087f1f6a53e62f6bac6cabe0a6c1368b4f) to /private/var/folders/p3/1ps_hr3569v1wkw8574_b0000000gn/T/pip-sS1uX7-build
  Could not find a tag or branch '86433d087f1f6a53e62f6bac6cabe0a6c1368b4f', assuming commit.
Installing collected packages: djangae
  Running setup.py install for djangae ... done
Successfully installed djangae-0.9.10a0

$ $HOME/dev/py_virtualenv/pt/bin/python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/seawolf/dev/py_virtualenv/pt/lib/python2.7/site-packages/djangae/core/management/__init__.py", line 62, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + other_args, **overrides)
  File "/Users/seawolf/dev/py_virtualenv/pt/lib/python2.7/site-packages/djangae/core/management/__init__.py", line 42, in _execute_from_command_line
    **sandbox_overrides
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/seawolf/dev/py_virtualenv/pt/lib/python2.7/site-packages/djangae/sandbox.py", line 434, in activate
    with SANDBOXES[sandbox_name](**kwargs):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/seawolf/dev/py_virtualenv/pt/lib/python2.7/site-packages/djangae/sandbox.py", line 177, in _local
    dispatcher = _create_dispatcher(configuration, options)
  File "/Users/seawolf/dev/py_virtualenv/pt/lib/python2.7/site-packages/djangae/sandbox.py", line 113, in _create_dispatcher
    dispatcher_args.insert(7, DevelopmentServer._create_go_config(options))
AttributeError: type object 'DevelopmentServer' has no attribute '_create_go_config'

```

I saw the same issue if I installed from master/HEAD:


```
$ pip install git+https://github.com/potatolondon/djangae.git
Collecting git+https://github.com/potatolondon/djangae.git
  Cloning https://github.com/potatolondon/djangae.git to /private/var/folders/p3/1ps_hr3569v1wkw8574_b0000000gn/T/pip-Z_ughZ-build
Installing collected packages: djangae
  Running setup.py install for djangae ... done
Successfully installed djangae-0.9.10a0

$ pip install git+https://github.com/potatolondon/djangae.git@86433d087f1f6a53e62f6bac6cabe0a6c1368b4f
Collecting git+https://github.com/potatolondon/djangae.git@86433d087f1f6a53e62f6bac6cabe0a6c1368b4f
  Cloning https://github.com/potatolondon/djangae.git (to 86433d087f1f6a53e62f6bac6cabe0a6c1368b4f) to /private/var/folders/p3/1ps_hr3569v1wkw8574_b0000000gn/T/pip-sS1uX7-build
  Could not find a tag or branch '86433d087f1f6a53e62f6bac6cabe0a6c1368b4f', assuming commit.
Installing collected packages: djangae
  Running setup.py install for djangae ... done
Successfully installed djangae-0.9.10a0

$ $HOME/dev/py_virtualenv/pt/bin/python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/seawolf/dev/py_virtualenv/pt/lib/python2.7/site-packages/djangae/core/management/__init__.py", line 62, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + other_args, **overrides)
  File "/Users/seawolf/dev/py_virtualenv/pt/lib/python2.7/site-packages/djangae/core/management/__init__.py", line 42, in _execute_from_command_line
    **sandbox_overrides
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/seawolf/dev/py_virtualenv/pt/lib/python2.7/site-packages/djangae/sandbox.py", line 514, in activate
    with SANDBOXES[sandbox_name](**kwargs):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/seawolf/dev/py_virtualenv/pt/lib/python2.7/site-packages/djangae/sandbox.py", line 216, in _local
    dispatcher = _create_dispatcher(configuration, options)
  File "/Users/seawolf/dev/py_virtualenv/pt/lib/python2.7/site-packages/djangae/sandbox.py", line 150, in _create_dispatcher
    dispatcher_args.insert(7, DevelopmentServer._create_go_config(options))
AttributeError: type object 'DevelopmentServer' has no attribute '_create_go_config'
```

**Comment by seawolf42** [comment]
I'm happy to close this whenever you have what you need... should I at least leave it open until 0.9.10 ships so that others can refer to it?

**Comment by Kazade** [comment]
It's fine, I'll close it now, if anyone else has the issue there'll hopefully find this explanation ;)
