### ISSUE TITLE
how to make a basic GAE app

### ISSUE THREAD

**Issue by cyrfer** [potatolondon/djangae#776]
Can someone help me get a basic Django app running locally, ready for use in the GAE standard environment?

I was lured by [this tutorial](https://github.com/GoogleCloudPlatform/appengine-django-skeleton), but because I cannot find details about the free tier for CloudSQL, I went looking for this project to help me leverage Cloud Datastore.

Attempting to setup a Djangae app,
* I started with the [scaffolding example](https://github.com/potatolondon/djangae-scaffold) but I was freaked out by its setup trying to download GAE, which is already installed locally (see gcloud).
* I followed [djangae instructions](https://djangae.readthedocs.io/en/latest/installation/) for "installation". The one change is that I needed to modify `manage.py` to find vendors in 'lib' folder.
* I attempted to setup a DB back-end, following [djangae instructions](https://djangae.readthedocs.io/en/latest/db_backend/).

My app structure looks like this:
- gitfolder
  - djangosite (outer)
    - app.yaml
    - manage.py
    - lib
      - django
      - djangae
    - djangosite (inner)
      - settings.py ...

Below is the error I see locally. 
----
$ python manage.py runserver
WARNING  2016-11-13 15:46:24,631 simple_search_stub.py:1146] Could not read search indexes from C:\Users\johnk_000\gitproject\djangosite\.storage\search_indexes
INFO     2016-11-13 15:46:24,799 blobstore_service.py:73] Starting blobstore service on localhost:8080
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "lib\djangae\core\management\__init__.py", line 65, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "lib\djangae\core\management\__init__.py", line 45, in _execute_from_command_line
    return django_management.execute_from_command_line(argv)
  File "lib\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "lib\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "lib\django\core\management\__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "lib\django\core\management\__init__.py", line 41, in load_command_class
    return module.Command()
  File "lib\djangae\management\commands\runserver.py", line 105, in __new__
    instance.option_list += (
AttributeError: 'Command' object has no attribute 'option_list'

**Comment by davidwtbuxton** [comment]
Hi,

What versions of Django and Djangae are you using? Django 1.10 doesn't work with Djangae 0.9.7 (see #749 ).

Assuming that is the same problem you are seeing, either downgrade to Django 1.9.x or use the current master version of Djangae, which has a fix.

David B.

**Comment by cyrfer** [comment]
@davidwtbuxton - I think you caught it. Thank you for the support.

I will test with Djangae from master and then close this if I am successful.

I wish Djangae would stamp a release that supports the latest Django.

**Comment by cyrfer** [comment]
I'm moving closer, I can feel it...

To fix the version compatibility problem, I found I could add the following to my `requirements.txt` file.
```
Django
https://github.com/potatolondon/djangae/archive/master.zip
```

I was not familiar with the `import` statement in Python. Apparently Python is also not familiar with it. The code `url(r'^_ah/', include('djangae.urls'))` from the [djangae installations instructions](https://djangae.readthedocs.io/en/latest/installation/) produces a mouthful of errors.

After digging around for a while, I found an [example](https://docs.djangoproject.com/en/1.10/topics/http/urls/#including-other-urlconfs) on Django's website that said it offers an `include` module, which can be imported like this:
`from django.conf.urls import include, url`

That import fixed my initialization run-time errors. Now I'm wondering if all is well. I'm new to Django, so I will look into their tutorial. I want to keep this issue open until I am sure I can serve a webpage.

**Comment by cyrfer** [comment]
I think I'm stuck again. I appreciate any help.

The good:
```
$ python manage.py runserver
WARNING  2016-11-14 23:06:10,398 simple_search_stub.py:1146] Could not read search indexes from C:\Users\johnk_000\gitproject\djangosite\.storage\search_indexes
INFO     2016-11-14 23:06:11,178 blobstore_service.py:73] Starting blobstore service on localhost:8080
Validating models...

System check identified no issues (0 silenced).
November 14, 2016 - 23:06:12
Django version 1.10.3, using settings 'djangosite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

INFO     2016-11-14 23:06:12,414 devappserver2.py:769] Skipping SDK update check.
INFO     2016-11-14 23:06:12,434 api_server.py:205] Starting API server at: http://127.0.0.1:8002
INFO     2016-11-14 23:06:12,448 dispatcher.py:197] Starting module "default" running at: http://localhost:8000
INFO     2016-11-14 23:06:12,450 admin_server.py:116] Starting admin server at: http://127.0.0.1:8001
```

The bad, when I try to open `http://localhost:8000`

```
INFO     2016-11-14 23:09:00,654 module.py:402] [default] Detected file changes:
  .storage\logs.db
  .storage\logs.db-journal
ERROR    2016-11-14 23:09:00,648 wsgi.py:263]
Traceback (most recent call last):
  File "C:\Users\johnk_000\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "C:\Users\johnk_000\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "C:\Users\johnk_000\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "C:\Users\johnk_000\Documents\clients\me\sellout.io\code\pint_consumer\djangosite\djangosite\wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
INFO     2016-11-14 23:09:00,671 runserver.py:323] default: "GET / HTTP/1.1" 500 -
INFO     2016-11-14 23:09:03,674 module.py:402] [default] Detected file changes:
  .storage
  .storage\logs.db-journal
```

**Comment by davidwtbuxton** [comment]
Hi,

Good to hear you got past the immediate requirements problem. The Djangae docs assume a familiarity with a conventional (non-App Engine) Django application setup. I recommend you at least complete [the Django tutorial][1], or another tutorial such as [the Django Girls tutorial][2] (it's not just for girls).

    ImportError: No module named django.core.wsgi

That error suggests either Django is not installed in your project's vendored libraries folder, or that your project has not setup the Python import path. Where is Django installed? Do you have code in `manage.py` and `wsgi.py` to add your vendored libraries path to `sys.path`?

Questions about using Djangae are more appropriate for [the Djangae users' forum][3]. This GitHub issues tracker is intended for discussion of bugs in Djangae itself.

Hope this helps,

David B.


[1]: https://docs.djangoproject.com/en/1.10/intro/tutorial01/
[2]: https://tutorial.djangogirls.org/en/
[3]: https://groups.google.com/forum/#!forum/djangae-users

**Comment by Kazade** [comment]
I hope you got this sorted, I'm going to close this issue - if you have any more questions contact the user's forum linked above.
